# grant superuser level permission
sudo: required

# install docker
services:
  - docker

before_install:
  - docker build -t klezca/docker-react -f Docker.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test