# grant superuser level permission
sudo: required

# install docker
services:
  - docker

before_install:
  - docker build -t klezca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true klezca/docker-react npm run test

deploy:
  provider: elasticbeanstalk  
  region: "ap-southeast-1"
  app: "docker-Frontend"
  env: "docker-Frontend-Dev"
  bucket_name: elasticbeanstalk-ap-southeast-1-748676708985
  bucket: "docker-Frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key:
    secure: $AWS_SECRET_KEY 
    