# grant superuser level permission
sudo: required

# install docker
services:
  - docker

before_install:
  - docker build -t klezca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true klezca/docker-react npm run test